name: Create and publish frontend package

on:
  workflow_dispatch:  # Manual trigger for flexibility

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: packages/in-preview-editing-support
        run: pnpm install

      - name: Build package
        working-directory: packages/in-preview-editing-support
        run: pnpm build

      - name: Pack package
        working-directory: packages/in-preview-editing-support
        run: pnpm pack

      - name: Get version from package.json
        id: get_version
        working-directory: packages/in-preview-editing-support
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: in-preview-editing-support v${{ steps.get_version.outputs.version }}
          files: packages/in-preview-editing-support/*.tgz
          body: |
            Frontend package for CoreMedia in-preview editing support.
            Please refer to the [documentation](packages/in-preview-editing-support/README.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate at npm.coremedia.io
        run: |
          echo "Authenticating with npm.coremedia.io..."
          echo "::debug::Requesting token for user: $NPM_USER"

          USERNAME="${NPM_USER:0:3}"
          echo "NPM user is: $USERNAME"

          PW="${NPM_PASSWORD:0:3}"
          echo "NPM password is: $PW"

          NPM_TOKEN=$(curl -s \
            -H "Accept: application/json" \
            -H "Content-Type:application/json" \
            -X PUT \
            --data "{\"name\": \"$NPM_USER\", \"password\": \"$NPM_PASSWORD\"}" \
            https://npm.coremedia.io/-/user/org.couchdb.user:$NPM_USER | jq -r .token)

          if [ -z "$NPM_TOKEN" ] || [ "$NPM_TOKEN" = "null" ]; then
            echo "❌ Failed to get token from npm.coremedia.io"
            exit 1
          fi

          TK="${NPM_TOKEN:0:5}"
          echo "NPM token is: $TK"

          echo "//npm.coremedia.io/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "registry=https://npm.coremedia.io/" >> ~/.npmrc
          echo "@coremedia-contributions:registry=https://npm.coremedia.io/" >> ~/.npmrc
          echo "✅ Authenticated successfully"
        env:
          NPM_USER: ${{ secrets.CM_NPM_USER }}
          NPM_PASSWORD: ${{ secrets.CM_NPM_PASSWORD }}

      - name: Publish package to npm.coremedia.io
        working-directory: packages/in-preview-editing-support
        run: pnpm publish --no-git-checks --registry=https://npm.coremedia.io/
